// <auto-generated />
using System;
using JaizBankPersistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JaizBankPersistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220913143229_Initialise")]
    partial class Initialise
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("JaizBankDomain.Entities.Transactions", b =>
                {
                    b.Property<Guid>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Amount")
                        .HasPrecision(20, 2)
                        .HasColumnType("decimal(20,2)");

                    b.Property<string>("AuthorizationCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DebitCardNo")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("ExpiryDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MerchantId")
                        .HasColumnType("int");

                    b.Property<string>("MerchantName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PTAD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RRN")
                        .HasColumnType("int");

                    b.Property<int>("ResponseCode")
                        .HasColumnType("int");

                    b.Property<int>("STAN")
                        .HasColumnType("int");

                    b.Property<string>("TerminalID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TransactionId");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            TransactionId = new Guid("f4c4c875-f854-44ab-8048-bf5fde41a482"),
                            AID = "A0000000041010",
                            Amount = 0.01m,
                            AuthorizationCode = "000000",
                            DateTime = new DateTime(2022, 8, 30, 13, 45, 0, 0, DateTimeKind.Unspecified),
                            DebitCardNo = "539941******3369",
                            ExpiryDate = "11/24",
                            Location = "NO, 174 NTA/MBUORA RD, PORTHARCOURT",
                            MerchantId = 0,
                            MerchantName = "LIZPEE GLOBAL RESOURCES",
                            PTAD = "Global Accelerex",
                            RRN = 210002450,
                            ResponseCode = 91,
                            STAN = 3862,
                            TerminalID = "23011845"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
